ci: update existing release candidate branch and pr if they already exist (#3222)
Current code for release candidate PR creation assumes that the branch
for the release candidate is not yet created. If this is run again, the
following error fails the update:

```
Run # Configure Git user identity for the workflow using the actor who triggered it
Already on 'release-v1.0.213'
Your branch is up to date with 'origin/release-v1.0.213'.
Switched to a new branch 'pre-release-v1.0.213-rc5'
[pre-release-v1.0.213-rc5 eae79a94] Pre-release commit for v1.0.213-rc5
To https://github.com/odigos-io/odigos
 ! [rejected]          pre-release-v1.0.213-rc5 -> pre-release-v1.0.213-rc5 (non-fast-forward)
error: failed to push some refs to 'https://github.com/odigos-io/odigos'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: Process completed with exit code 1.
```

This PR handles both cases:
-  release branch exist (update it to point to the release branch HEAD)
- release branch not exist (create it from release branch HEAD)