CORE-1023: Add externalOnpremPullSecret helm value (#5145)
#### What this PR does / why we need it:
Using `externalOnpremTokenSecret: true` with the new enterprise Docker
pull secret generation added in
https://github.com/odigos-io/odigos/pull/4990 can cause errors like:

```
ComparisonError: Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): `helm template . --name-template odigos-qa --namespace odigos --kube-version 1.34 --values <path to cached source>/apps/odigos/values-qa.yml <api versions removed> --include-crds` failed exit status 1: Error: execution error at (odigos/charts/odigos/templates/validate-enterprise-pull-secrets.yaml:1:3): Odigos images pull from registry.odigos.io but no on-prem token is available to the chart. Set onPremToken or ensure the odigos-pro secret exists in the release namespace before install/upgrade. Use --debug flag to render out invalid YAML
```

In this case, with an Argo deployment, where Argo is unable to read the
token secret value (even though the secret exists). This is actually the
only place where we are trying to *read* the secret value (in order to
generate the Docker pull secret based off the onprem token). Other spots
just assume it exists if `externalOnpremTokenSecret: true` and sets up
the appropriate enterprise mounts.

This `externalOnpremPullSecret` works the same way. If it is `true`, the
helm chart will assume the externally-managed Docker pull secret exists
and set up the required mounts. This does put the burden on certain
users to create the pull secret themselves, which is why this PR also
adds documentation on how to do that.

cherry-pick:v1.30

#### Changelog entry: Does this PR introduce a user-facing bug fix,
feature, dependency update, or breaking change??
<!--
This section will go in the release notes for this version. Is this
something users should be able to find easily?
If no, just write "NONE" in the release-note block below.
If yes, please add a release note in the block below describing this in
1-2 sentences for our changelog.
-->

```release-note
fix: add externalOnpremPullSecret for enterprise Docker pull secret management
```