ci: update the names of the sts files (#4478)
#### What this PR does / why we need it:

To fix from #4477 which claims:

```
Error: STS exchange failed for odigos-io/odigos/ro: HTTP 404 — {"code":5, "message":"unable to find trust policy for \"ro\"", "details":[]}
```


#### Changelog entry: Does this PR introduce a user-facing bug fix,
feature, dependency update, or breaking change??
<!--
This section will go in the release notes for this version. Is this
something users should be able to find easily?
If no, just write "NONE" in the release-note block below.
If yes, please add a release note in the block below describing this in
1-2 sentences for our changelog.
-->

```release-note
NONE
```