CORE-827: Fix preflight workflow (#4500)
#### What this PR does / why we need it:

https://github.com/odigos-io/odigos/pull/4496 updated the preflight job
with component selection and dry run checking

It failed with:

```
TypeError: Cannot read properties of undefined (reading 'payload')
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:36187:16), <anonymous>:16:31)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:36188:12)
    at main (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:36285:26)
    at /home/runner/work/_actions/actions/github-script/v7/dist/index.js:36260:1
    at /home/runner/work/_actions/actions/github-script/v7/dist/index.js:36317:3
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:36320:12)
    at Module._compile (node:internal/modules/cjs/loader:1521:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)
    at Module.load (node:internal/modules/cjs/loader:1266:32)
    at Module._load (node:internal/modules/cjs/loader:1091:12)
Error: Unhandled error: TypeError: Cannot read properties of undefined (reading 'payload')
```

The workflow should use `context.payload` instead of
`github.context.payload`

See
https://github.com/odigos-io/odigos/actions/runs/23612613901/job/68771988978#step:2:51

#### Changelog entry: Does this PR introduce a user-facing bug fix,
feature, dependency update, or breaking change??
<!--
This section will go in the release notes for this version. Is this
something users should be able to find easily?
If no, just write "NONE" in the release-note block below.
If yes, please add a release note in the block below describing this in
1-2 sentences for our changelog.
-->

```release-note
NONE
```