odiglet: Handle re-running semanage on openshift (#2634)
## Description

User reported Odiglet init containers failing on OpenShift with the
following:

```
{"level":"error","ts":1742824305.449013,"caller":"fs/agents.go:159","msg":"Error running semanage command","error":"exit status 1","stacktrace":"[github.com/odigos-io/odigos/odiglet/pkg/instrumentation/fs.ApplyOpenShiftSELinuxSettings\n\t/go/pkg/mod/github.com/odigos-io/odigos/odiglet@v1.0.162/pkg/instrumentation/fs/agents.go:159\ngithub.com/odigos-io/odigos/odiglet.OdigletInitPhase\n\t/go/pkg/mod/github.com/odigos-io/odigos/odiglet@v1.0.162/odiglet.go:203\nmain.main\n\t/go/src/github.com/odigos-io/odigos-enterprise/odiglet/cmd/enterprise/main.go:42\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:272](http://github.com/odigos-io/odigos/odiglet/pkg/instrumentation/fs.ApplyOpenShiftSELinuxSettings%5Cn%5Ct/go/pkg/mod/github.com/odigos-io/odigos/odiglet@v1.0.162/pkg/instrumentation/fs/agents.go:159%5Cngithub.com/odigos-io/odigos/odiglet.OdigletInitPhase%5Cn%5Ct/go/pkg/mod/github.com/odigos-io/odigos/odiglet@v1.0.162/odiglet.go:203%5Cnmain.main%5Cn%5Ct/go/src/github.com/odigos-io/odigos-enterprise/odiglet/cmd/enterprise/main.go:42%5Cnruntime.main%5Cn%5Ct/usr/local/go/src/runtime/proc.go:272)"}
{"level":"error","ts":1742824305.4491239,"caller":"odiglet@v1.0.162/odiglet.go:204","msg":"Failed to apply SELinux settings on RHEL host","error":"exit status 1","stacktrace":"[github.com/odigos-io/odigos/odiglet.OdigletInitPhase\n\t/go/pkg/mod/github.com/odigos-io/odigos/odiglet@v1.0.162/odiglet.go:204\nmain.main\n\t/go/src/github.com/odigos-io/odigos-enterprise/odiglet/cmd/enterprise/main.go:42\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:272](http://github.com/odigos-io/odigos/odiglet.OdigletInitPhase%5Cn%5Ct/go/pkg/mod/github.com/odigos-io/odigos/odiglet@v1.0.162/odiglet.go:204%5Cnmain.main%5Cn%5Ct/go/src/github.com/odigos-io/odigos-enterprise/odiglet/cmd/enterprise/main.go:42%5Cnruntime.main%5Cn%5Ct/usr/local/go/src/runtime/proc.go:272)"}
```

Further investigation on the host showed that the semanage context
already existed, and trying to run this was returning an error:

```
$ semanage fcontext -a -t container_ro_file_t '/var/odigos(/.*)?'
ValueError: File context for /var/odigos(/.*)? already defined
$ echo $?
1
```

This suggests that re-installing causes the error.

This doesn't seem to always be the case. In my test openshift
environment, selinux returns a `0` status code when this happens and
instead just modifies the existing context:

```
$ semanage fcontext -a -t container_ro_file_t '/var/odigos(/.*)?'
File context for /var/odigos(/.*)? already defined, modifying instead
```

So, this may be version dependent on the Linux host itself. This PR just
adds a check for `already defined` in the stdout text, and also improves
the logging around these openshift settings

## How Has This Been Tested?

<!-- Describe the tests you ran and how you verified your changes. -->

- [ ] Added Unit Tests
- [ ] Updated e2e Tests
- [x] Manual Testing
- [ ] Manual Load Test

## Kubernetes Checklist

<!-- If this PR affects how Odigos interacts with Kubernetes, check the
relevant boxes below and provide more details -->

- [ ] Changes how Odigos interacts with Kubernetes
- [ ] Introduces additional calls to the API Server (potential
performance impact)
- [ ] New Query/feature supported in all the k8s versions supported by
Odigos
- [ ] Modifies Odigos manifests (addressed in both CLI and Helm)
- [ ] Changes RBAC permissions

## User Facing Changes

<!-- Any changes that users will notice or need to be aware of -->

- [ ] Users need to take action before upgrading
- [ ] Automatic migration will modify existing objects (backward
compatible)
- [ ] Changes UI, CLI, or K8s Manifests aspects in a way that users need
to be aware of
- [ ] Documentation updated accordingly