CORE-554: Add TLS settings to Clickhouse destination + Update collector/otel to 141 + Remove deprecated components + Bump k8s min version to 1.21 (#4111)
The clickhouse exporter supports TLS settings similar to otlp:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/945e5a71ef31793ff3280b28c1425086ea5332b6/exporter/clickhouseexporter/README.md#tls

Some users need this to connect to clickhouse, adding them as options in
the destination here

This adds:

* `insecure_skip_verify`
* `ca_file` (using the k8sconfig interface to mount the secret as a
file, similar to how the GCP exporter supports application default
credentials)

The direct string fields (such as CAPem, CertPem, KeyPem) aren't yet
supported in the clickhouse exporter, so it has to be a mounted file.
See
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/43911#issuecomment-3786537702

---

To do this, it required bumping the collector/otel deps to 136 when TLS
config support was added to clickhouse. This required the following
changes:

This actually needs collector v0.136.0 for these settings from
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/42581
(https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/d9769f7c1a0f3bea82c711af551d9b5b44d69e6f)

Also needs to remove loki exporter (removed in 131) for 136 🙃
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/41413,
see
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.130.0/exporter/lokiexporter#deprecation-notice
it's replaced with just otlp. The only destination that actually looks
like it's using the loki exporter is OpsVerse

As well as the opencensus exporter, removed in 133 upstream by
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/42239

Also routing processor
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36616

See previous attempt https://github.com/odigos-io/odigos/pull/3669
(reverted in https://github.com/odigos-io/odigos/pull/3734)

---

Then, it turns out that 136 was bugged and did not have full support for
TLS settings like `insecure_skip_verify`. This was fixed in 141, which
required the following extra changes:

Actually needs collector v141 due to this bug in clickhouse not handling
all tls settings:
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/43911
fixed in
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/44093

Remove deprecated carbon exporter support (unmaintained upstream)
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/44532

another upstream breaking change giving go mod trouble
https://github.com/open-telemetry/opentelemetry-collector/pull/13948

configgrpc update:
https://github.com/open-telemetry/opentelemetry-collector/pull/13996

and now metadata.yaml metrics require stablity levels
https://github.com/open-telemetry/opentelemetry-collector/pull/13756

```
Error: failed loading /app/collector/receivers/odigosebpfreceiver/metadata.yaml: decoding failed due to the following error(s):

'telemetry.metrics[ebpf_memory_pressure_wait_time_total]' missing required field: `stability`
'telemetry.metrics[ebpf_total_bytes_read]' missing required field: `stability`
'telemetry.metrics[ebpf_lost_samples]' missing required field: `stability`
Error: failed loading /app/collector/receivers/odigosebpfreceiver/metadata.yaml: decoding failed due to the following error(s):

'telemetry.metrics[ebpf_memory_pressure_wait_time_total]' missing required field: `stability`
'telemetry.metrics[ebpf_total_bytes_read]' missing required field: `stability`
'telemetry.metrics[ebpf_lost_samples]' missing required field: `stability`
Error: metadata.yaml ordering check failed: [telemetry metrics] keys are not sorted: [odigos_log_data_size odigos_metric_data_size odigos_trace_data_size odigos_accepted_spans odigos_accepted_metric_points odigos_accepted_log_records]
Error: metadata.yaml ordering check failed: [telemetry metrics] keys are not sorted: [odigos_log_data_size odigos_metric_data_size odigos_trace_data_size odigos_accepted_spans odigos_accepted_metric_points odigos_accepted_log_records]
```

This bump also required adding the `endpointslices` permission to the
odiglet service account for the data-collection collector

---

Finally, endpointslices was not GA in k8s 1.20. This PR bumps our
minimum supported k8s version to 1.21. Enterprise update in
https://github.com/odigos-io/odigos-enterprise/pull/2117