CORE-827: Add short_commit to rhel cli job (#4495)
#### What this PR does / why we need it:
RHEL cli publish fails:
https://github.com/odigos-io/odigos/actions/runs/23601369557/job/68734021825#step:6:38

```
Run ko build --bare --tags latest --tags v1.22.1 \
  ko build --bare --tags latest --tags v1.22.1 \
  --image-label name=odigos-cli \
  --image-label vendor=Odigos \
  --image-label maintainer=Odigos \
  --image-label version=v1.22.1 \
  --image-label release=v1.22.1 \
  --image-label summary="Odigos CLI" \
  --image-label description="Odigos CLI to install and manage Odigos in your Kubernetes cluster." \
  --platform=all .
  shell: /usr/bin/bash -e {0}
  env:
    CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: /home/runner/work/odigos/odigos/gha-creds-4649cd135535968a.json
    GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/odigos/odigos/gha-creds-4649cd135535968a.json
    GOOGLE_GHA_CREDS_PATH: /home/runner/work/odigos/odigos/gha-creds-4649cd135535968a.json
    CLOUDSDK_CORE_PROJECT: odigos-cloud
    CLOUDSDK_PROJECT: odigos-cloud
    GCLOUD_PROJECT: odigos-cloud
    GCP_PROJECT: odigos-cloud
    GOOGLE_CLOUD_PROJECT: odigos-cloud
    KO_DOCKER_REPO: us-central1-docker.pkg.dev/odigos-cloud/components/odigos-cli-rhel-certified
    KO_CONFIG_PATH: ./.ko.yaml
    VERSION: v1.22.1
    KO_DEFAULTBASEIMAGE: registry.access.redhat.com/ubi9/ubi-micro:latest
2026/03/26 15:11:20 Using base registry.access.redhat.com/ubi9/ubi-micro:latest@sha256:2173487b3b72b1a7b11edc908e9bbf1726f9df46a4f78fd6d19a2bab0a701f38 for github.com/odigos-io/odigos/cli
2026/03/26 15:11:20 Using build config cli for github.com/odigos-io/odigos/cli
2026/03/26 15:11:20 Using build config cli for github.com/odigos-io/odigos/cli
2026/03/26 15:11:20 Using build config cli for github.com/odigos-io/odigos/cli
2026/03/26 15:11:21 git doesn't contain any tags. Tag info will not be available
git is in a dirty state
Please check in your pipeline what can be changing the following files:

2026/03/26 15:11:21 git doesn't contain any tags. Tag info will not be available
git is in a dirty state
Please check in your pipeline what can be changing the following files:

Error: failed to publish images: error building "ko://github.com/odigos-io/odigos/cli": build: template: argsTmpl:1:59: executing "argsTmpl" at <.Env.SHORT_COMMIT>: map has no entry for key "SHORT_COMMIT"
Error: Process completed with exit code 1.
```

#### Changelog entry: Does this PR introduce a user-facing bug fix,
feature, dependency update, or breaking change??
<!--
This section will go in the release notes for this version. Is this
something users should be able to find easily?
If no, just write "NONE" in the release-note block below.
If yes, please add a release note in the block below describing this in
1-2 sentences for our changelog.
-->

```release-note
NONE
```