CORE-171: Add Operator to promote-rc job (#3393)
The operator image isn't present in the promote-rc job, leading to
failures [like
this](https://github.com/odigos-io/odigos/actions/runs/17355701191/job/49268355288)
which cancel all of the other preflight submissions, because the
promoted tag isn't found

```
Error: invalid manifest?: GET https://registry.odigos.io/v2/odigos-operator-ubi9/manifests/v1.2.0: MANIFEST_UNKNOWN: Failed to fetch "v1.2.0"
```

This also updates the flags in the preflight job to fix this warning:

```
Flag --certification-project-id has been deprecated, please use --certification-component-id instead
```

## Description

<!-- Short summary of the changes -->

## How Has This Been Tested?

<!-- Describe the tests you ran and how you verified your changes. -->

- [ ] Added Unit Tests
- [ ] Updated e2e Tests
- [x] Manual Testing
- [ ] Manual Load Test

## Kubernetes Checklist

<!-- If this PR affects how Odigos interacts with Kubernetes, check the
relevant boxes below and provide more details -->

- [ ] Changes how Odigos interacts with Kubernetes
- [ ] Introduces additional calls to the API Server (potential
performance impact)
- [ ] New Query/feature supported in all the k8s versions supported by
Odigos
- [ ] Modifies Odigos manifests (addressed in both CLI and Helm)
- [ ] Changes RBAC permissions

## User Facing Changes

<!-- Any changes that users will notice or need to be aware of -->

- [ ] Users need to take action before upgrading
- [ ] Automatic migration will modify existing objects (backward
compatible)
- [ ] Changes UI, CLI, or K8s Manifests aspects in a way that users need
to be aware of
- [ ] Documentation updated accordingly

Co-authored-by: Amir Blum <amirgiraffe@gmail.com>