ci: fix flaky UI tests (#2611)
## Description

The UI tests are encountering 4 flakes, 2 of which occur often, and 2 of
which occur rarely.
The 4 flakes are documented in Notion:
https://www.notion.so/keyval/GEN-2443

This PR attempts to solve the flakes by adjusting the viewport (for
"element hidden from view" flakes), applying "force=true" on node-click
(for "element is covered" flakes), and by retrying once (for the other
flakes).

For example, this flake fails to update the 2nd source in list:
```bash
Sources CRUD
✓ Should have 0 sources.odigos.io CRDs in the cluster (770ms)
✓ Should have 0 instrumentationconfigs.odigos.io CRDs in the cluster (296ms)
✓ Should instrument 5 sources via API, and notify with SSE (7667ms)
✓ Should have 5 sources.odigos.io CRDs in the cluster (167ms)
✓ Should have 5 instrumentationconfigs.odigos.io CRDs in the cluster (163ms)
1) Should update the name of 5 sources via API, and notify locally
2) Should update "otelServiceName" of 5 sources.odigos.io CRDs in the cluster
3) Should update "serviceName" of 5 instrumentationconfigs.odigos.io CRDs in the cluster
✓ Should uninstrument 5 sources via API, and notify with SSE (10329ms)
✓ Should have 0 sources.odigos.io CRDs in the cluster (173ms)
✓ Should have 0 instrumentationconfigs.odigos.io CRDs in the cluster (170ms)

8 passing (33s)
3 failing

1) Sources CRUD
Should update the name of 5 sources via API, and notify locally:

CypressError: Timed out retrying after 4050ms: `cy.click()` failed because this element:
`<div data-id="source-1" class="sc-gosGQK kTqeKP nowheel nodrag">...</div>`

is being covered by another element:
`<div class="sc-bitXml hNjxoD">...</div>`

Fix this problem, or use {force: true} to disable error checking.
```

And with this PR, that same flake passed with the retry config, as seen
here:
```bash
Sources CRUD
✓ Should have 0 sources.odigos.io CRDs in the cluster (322ms)
✓ Should have 0 instrumentationconfigs.odigos.io CRDs in the cluster (167ms)
✓ Should instrument 5 sources via API, and notify with SSE (8257ms)
✓ Should have 5 sources.odigos.io CRDs in the cluster (169ms)
✓ Should have 5 instrumentationconfigs.odigos.io CRDs in the cluster (169ms)
(Attempt 1 of 2) Should update the name of 5 sources via API, and notify locally
✓ Should update the name of 5 sources via API, and notify locally (32174ms)
✓ Should update "otelServiceName" of 5 sources.odigos.io CRDs in the cluster (13807ms)
✓ Should update "serviceName" of 5 instrumentationconfigs.odigos.io CRDs in the cluster (1033ms)
✓ Should uninstrument 5 sources via API, and notify with SSE (7003ms)
✓ Should have 0 sources.odigos.io CRDs in the cluster (177ms)
✓ Should have 0 instrumentationconfigs.odigos.io CRDs in the cluster (178ms)
```

## How Has This Been Tested?

- [ ] Added Unit Tests
- [x] Updated e2e Tests
- [ ] Manual Testing
- [ ] Manual Load Test